# Auto-generated by setup_task.ps1 鈥?DO NOT EDIT MANUALLY.
# Launches the RPA data check silently for Task Scheduler.
# Triggered via: powershell.exe -WindowStyle Hidden -ExecutionPolicy Bypass -NoProfile -File <this>
$ErrorActionPreference = 'Stop'
Set-Location 'e:\AI\pythonProject\aiAutoTest'
& 'e:\AI\pythonProject\aiAutoTest\.venv\Scripts\python.exe' 'E:\AI\pythonProject\aiAutoTest\.claude\skills\prod-rpa-checker\run_check.py'
exit $LASTEXITCODE
