# Auto-generated by setup_dual_task.ps1 — DO NOT EDIT MANUALLY.
# 静默启动 RPA 数据校验，供 Task Scheduler 调用。
# 自包含：通过 $MyInvocation.MyCommand.Path 派生所有路径。
#
# 调用约定（由 setup 任务的 -ArgumentList 传入）：
#   $args[0] = config rel path (如 doc/数据中心类型定义am.json)
#   $args[1] = tag (morning / afternoon)

$ErrorActionPreference = 'Stop'

$SkillDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = (Get-Item $SkillDir).Parent.Parent.Parent.FullName
$VenvPython = Join-Path $ProjectRoot ".venv\Scripts\python.exe"

Set-Location $ProjectRoot
& $VenvPython "$SkillDir\scripts\run_scheduled_check.py" --config $args[0] --tag $args[1]
exit $LASTEXITCODE
