# Auto-generated by setup_dual_task.ps1 — DO NOT EDIT MANUALLY.
# 静默启动 RPA 数据校验，供 Task Scheduler 调用。
$ErrorActionPreference = 'Stop'
Set-Location 'e:\AI\pythonProject\aiAutoTest'
& 'e:\AI\pythonProject\aiAutoTest\.venv\Scripts\python.exe' 'E:\AI\pythonProject\aiAutoTest\.claude\skills\prod-rpa-checker\scripts\run_morning_check.py'
exit $LASTEXITCODE
