# setup_dual_task.ps1 - Register two Windows Scheduled Tasks (RPA data check)
#
# 为上午/下午两个时点注册独立任务，共用单一自包含 launcher：
#   - 上午 08:35  →  run_silent.ps1 + am.json + morning
#   - 下午 17:15  →  run_silent.ps1 + pm.json + afternoon
#
# run_silent.ps1 自包含：通过 $MyInvocation.MyCommand.Path 派生所有路径，
# 不依赖任何绝对路径，方便跨机器/跨盘符移植。
#
# 用法（需管理员 PowerShell，PowerShell 5.1 需先 chcp 65001 切 UTF-8）：
#   chcp 65001 | Out-Null
#   .\setup_dual_task.ps1 -ProjectDir "e:\AI\pythonProject\aiAutoTest"
#
# 可选参数：
#   -AtMorning         上午时点（默认 08:35）
#   -AtAfternoon       下午时点（默认 17:15）
#   -TaskNameMorning   上午任务名（默认 RPA-Data-Check-Morning）
#   -TaskNameAfternoon 下午任务名（默认 RPA-Data-Check-Afternoon）

param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectDir,

    [string]$AtMorning = "08:35",
    [string]$AtAfternoon = "17:15",

    [string]$TaskNameMorning = "RPA-Data-Check-Morning",
    [string]$TaskNameAfternoon = "RPA-Data-Check-Afternoon",

    [string]$VenvDir = ".venv",

    [string]$LegacyTaskName = "RPA Data Check Daily"
)

# Auto-locate skill directory（脚本所在目录）
$SkillDir = $PSScriptRoot

# ---------------------------------------------------------------------------
# 路径校验
# ---------------------------------------------------------------------------
$ScheduledScript = Join-Path $SkillDir "scripts\run_scheduled_check.py"
$LauncherPath = Join-Path $SkillDir "run_silent.ps1"
$VenvPython = Join-Path $ProjectDir "$VenvDir\Scripts\python.exe"

if (-not (Test-Path $ScheduledScript)) {
    Write-Error "未找到: $ScheduledScript"; exit 1
}
if (-not (Test-Path $VenvPython)) {
    Write-Error "未找到虚拟环境: $VenvPython"; exit 1
}

$envFile = Join-Path $ProjectDir ".env"
if (-not (Test-Path $envFile)) {
    Write-Warning ".env not found at $envFile — 请确认 FEISHU_WEBHOOK_URL 等已配置"
} else {
    Write-Host "  ENV     : $envFile ✓"
}

Write-Host "  Project : $ProjectDir"
Write-Host "  Skill   : $SkillDir"
Write-Host "  Python  : $VenvPython"
Write-Host "  Script  : $ScheduledScript"
Write-Host ""

# ---------------------------------------------------------------------------
# 清理旧的单任务（如存在）—— 避免重复触发同一脚本
# ---------------------------------------------------------------------------
if ($LegacyTaskName -and (Get-ScheduledTask -TaskName $LegacyTaskName -ErrorAction SilentlyContinue)) {
    Unregister-ScheduledTask -TaskName $LegacyTaskName -Confirm:$false
    Write-Host "[清理] 已删除旧任务: $LegacyTaskName"
    Write-Host ""
}

# ---------------------------------------------------------------------------
# 创建统一 launcher .ps1（自包含 + 参数化）
# 不再生成两份 launcher；run_silent.ps1 通过 $args 区分 am/pm
# ---------------------------------------------------------------------------
function New-OrUpdate-Launcher([string]$Path) {
    # 用单引号 here-string：不展开变量、不解析内嵌双引号 → launcher 自包含
    $Content = @'
# Auto-generated by setup_dual_task.ps1 — DO NOT EDIT MANUALLY.
# 静默启动 RPA 数据校验，供 Task Scheduler 调用。
# 自包含：通过 $MyInvocation.MyCommand.Path 派生所有路径。
#
# 调用约定（由 setup 任务的 -ArgumentList 传入）：
#   $args[0] = config rel path (如 doc/数据中心类型定义am.json)
#   $args[1] = tag (morning / afternoon)

$ErrorActionPreference = 'Stop'

$SkillDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = (Get-Item $SkillDir).Parent.Parent.Parent.FullName
$VenvPython = Join-Path $ProjectRoot ".venv\Scripts\python.exe"

Set-Location $ProjectRoot
& $VenvPython "$SkillDir\scripts\run_scheduled_check.py" --config $args[0] --tag $args[1]
exit $LASTEXITCODE
'@
    if (-not (Test-Path $Path)) {
        Set-Content -Path $Path -Value $Content -Encoding UTF8
        Write-Host "  Launcher: Created $Path"
    } else {
        $Existing = Get-Content -Path $Path -Raw -Encoding UTF8
        if ($Existing.Trim() -ne $Content.Trim()) {
            Set-Content -Path $Path -Value $Content -Encoding UTF8
            Write-Host "  Launcher: Updated $Path"
        } else {
            Write-Host "  Launcher: Up-to-date (skipped)"
        }
    }
}

New-OrUpdate-Launcher $LauncherPath

# 清理旧的 launcher（如存在）—— 不再使用
$OldLaunchers = @(
    (Join-Path $SkillDir "run_morning_silent.ps1"),
    (Join-Path $SkillDir "run_afternoon_silent.ps1")
)
foreach ($Old in $OldLaunchers) {
    if (Test-Path $Old) {
        Remove-Item $Old -Force
        Write-Host "  Launcher: Removed legacy $Old"
    }
}

Write-Host ""

# ---------------------------------------------------------------------------
# 公共配置 — 双任务共用的任务计划参数
#   AllowStartIfOnBatteries      允许电池模式下运行（笔记本插电/电池都能触发）
#   DontStopIfGoingOnBatteries   切电池时不中断正在执行的任务
#   WakeToRun                    唤醒睡眠中的电脑（早 08:35 任务需要）
#   RestartCount = 3             失败时自动重试 3 次
#   RestartInterval = 5min       重试间隔
#   ExecutionTimeLimit = 30min   单次执行不超过 30 分钟（超时强杀，防止挂起）
#
# ⚠️ 注意事项：PowerShell 反引号 ` 是行继续符，中间插入注释行（# 开头）
#   会中断继续链，导致后续参数被当作独立命令解析，CommonSettings 会
#   退化为默认值（不报错但参数丢失）。所以这里把注释放在调用之前。
# ---------------------------------------------------------------------------
$CommonSettings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -WakeToRun `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 5) `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 30)

$Principal = New-ScheduledTaskPrincipal `
    -UserId $env:USERNAME `
    -LogonType Interactive `
    -RunLevel Limited

# ---------------------------------------------------------------------------
# 任务列表
# ---------------------------------------------------------------------------
$Tasks = @(
    @{
        Name        = $TaskNameMorning
        Time        = $AtMorning
        ConfigRel   = "doc/数据中心类型定义am.json"
        Tag         = "morning"
        Description = "RPA 数据校验（上午 $AtMorning） — 使用 am.json（旧时间值）"
    },
    @{
        Name        = $TaskNameAfternoon
        Time        = $AtAfternoon
        ConfigRel   = "doc/数据中心类型定义pm.json"
        Tag         = "afternoon"
        Description = "RPA 数据校验（下午 $AtAfternoon） — 使用 pm.json（新时间值，整体后移 1 天）"
    }
)

foreach ($Task in $Tasks) {
    $Action = New-ScheduledTaskAction `
        -Execute "powershell.exe" `
        -Argument "-WindowStyle Hidden -ExecutionPolicy Bypass -NoProfile -File `"$LauncherPath`" `"$($Task.ConfigRel)`" `"$($Task.Tag)`"" `
        -WorkingDirectory $ProjectDir
    $Trigger = New-ScheduledTaskTrigger -Daily -At $Task.Time

    Register-ScheduledTask `
        -TaskName $Task.Name `
        -Action $Action `
        -Trigger $Trigger `
        -Settings $CommonSettings `
        -Principal $Principal `
        -Description $Task.Description `
        -Force | Out-Null

    Write-Host ""
    Write-Host "[OK] 注册任务: $($Task.Name)"
    Write-Host "  时点    : $($Task.Time)"
    Write-Host "  Config  : $($Task.ConfigRel)"
    Write-Host "  Tag     : $($Task.Tag)"
    Write-Host "  Launcher: $LauncherPath"
    Write-Host "  描述    : $($Task.Description)"
}

Write-Host ""
Write-Host "=========================================================="
Write-Host "两个任务注册完成！"
Write-Host "=========================================================="
Write-Host ""
Write-Host "手动触发测试（立即执行一次）："
Write-Host "  Start-ScheduledTask -TaskName '$TaskNameMorning'"
Write-Host "  Start-ScheduledTask -TaskName '$TaskNameAfternoon'"
Write-Host ""
Write-Host "查看任务状态："
Write-Host "  Get-ScheduledTask -TaskName '$TaskNameMorning'"
Write-Host "  Get-ScheduledTask -TaskName '$TaskNameAfternoon'"
Write-Host ""
Write-Host "删除任务（如需）："
Write-Host "  Unregister-ScheduledTask -TaskName '$TaskNameMorning' -Confirm:`$false"
Write-Host "  Unregister-ScheduledTask -TaskName '$TaskNameAfternoon' -Confirm:`$false"
