# setup_task.ps1 - Register Windows Scheduled Task (run once)
# Usage: .\setup_task.ps1 -ProjectDir "e:\AI\pythonProject\aiAutoTest" -At "17:10"

param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectDir,

    [string]$At = "17:10",

    [string]$At2 = $null,

    [string]$TaskName = "RPA Data Check Daily",

    [string]$VenvDir = ".venv"
)

# Auto-locate skill directory (where this script lives)
$SkillDir = Split-Path $MyInvocation.MyCommand.Path -Parent
$RunCheck = Join-Path $SkillDir "run_check.py"

# Validate paths
if (-not (Test-Path $RunCheck)) {
    Write-Error "run_check.py not found: $RunCheck"
    exit 1
}
$envFile = Join-Path $ProjectDir ".env"
if (-not (Test-Path $envFile)) {
    Write-Warning "WARNING: .env not found at $envFile. Please configure FEISHU_WEBHOOK_URL."
}

# Resolve venv python path (absolute, no PATH dependency)
$VenvPython = Join-Path $ProjectDir "$VenvDir\Scripts\python.exe"
if (-not (Test-Path $VenvPython)) {
    Write-Error "Virtual environment Python not found at: $VenvPython"
    exit 1
}

# ---------------------------------------------------------------------------
# Create a PowerShell launcher to ensure absolute zero window flashing
# and correct working directory.
#
# Why PowerShell instead of wscript.exe + VBS?
#   On Windows 11 (build 26100), Task Scheduler launching wscript.exe + VBS
#   hangs at WshShell.Run before the child python.exe ever starts. Reproduced
#   3 times on 2026-06-08 (19:00 S4U, 19:25 S4U, 19:43 Interactive) — wscript
#   stuck with 47–109ms CPU, zero child process, sentinel file untouched,
#   regardless of -LogonType. Manually invoking the same wscript+VBS from cmd
#   works fine, so the bug is specific to Task Scheduler's hosted session.
#   powershell.exe -WindowStyle Hidden uses Process.Start (not WSH/COM) to
#   spawn python and proved reliable.
#
# VBS file (run_check_silent.vbs) is intentionally NOT deleted — kept as a
# historical reference and for manual debugging via cmd.
# ---------------------------------------------------------------------------
$LauncherPs1 = Join-Path $SkillDir "run_check_silent.ps1"

# Inside single-quoted PowerShell strings, ' is escaped as ''.
# These paths contain no single quotes, so direct substitution is safe.
$ExpectedPs1Content = @"
# Auto-generated by setup_task.ps1 — DO NOT EDIT MANUALLY.
# Launches the RPA data check silently for Task Scheduler.
# Triggered via: powershell.exe -WindowStyle Hidden -ExecutionPolicy Bypass -NoProfile -File <this>
`$ErrorActionPreference = 'Stop'
Set-Location '$ProjectDir'
& '$VenvPython' '$RunCheck'
exit `$LASTEXITCODE
"@

# Only regenerate when content changed (preserve mtime, allow safe re-runs)
if (-not (Test-Path $LauncherPs1)) {
    Set-Content -Path $LauncherPs1 -Value $ExpectedPs1Content -Encoding UTF8
    Write-Host "  PS1     : Created $LauncherPs1"
} else {
    $ExistingPs1Content = Get-Content -Path $LauncherPs1 -Raw -Encoding UTF8
    if ($ExistingPs1Content.Trim() -ne $ExpectedPs1Content.Trim()) {
        Set-Content -Path $LauncherPs1 -Value $ExpectedPs1Content -Encoding UTF8
        Write-Host "  PS1     : Updated $LauncherPs1 (paths changed)"
    } else {
        Write-Host "  PS1     : Up-to-date (skipped)"
    }
}

# Task Action: powershell -WindowStyle Hidden produces no visible window and
# bypasses the WSH/COM path that hangs under Task Scheduler.
$action = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-WindowStyle Hidden -ExecutionPolicy Bypass -NoProfile -File `"$LauncherPs1`"" `
    -WorkingDirectory $ProjectDir

$trigger1 = New-ScheduledTaskTrigger -Daily -At $At

if ($At2) {
    $trigger2 = New-ScheduledTaskTrigger -Daily -At $At2
    $triggers = @($trigger1, $trigger2)
    $triggerDescription = "Daily at $At and $At2"
} else {
    $triggers = @($trigger1)
    $triggerDescription = "Daily at $At"
}

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -WakeToRun `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 5) `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 30)

# Principal: run only when user is logged on (Interactive avoids S4U hang on
# wscript under Win11 26100 — wscript+VBS blocks at WshShell.Run forever under
# S4U, observed 2026-06-08 19:00 & 19:25 with identical 47ms-CPU/30min-timeout).
$principal = New-ScheduledTaskPrincipal `
    -UserId $env:USERNAME `
    -LogonType Interactive `
    -RunLevel Limited

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $triggers `
    -Settings $settings `
    -Principal $principal `
    -Description "RPA data check at $triggerDescription, push result to Feishu group (Silent, wakes from sleep)" `
    -Force

Write-Host ""
Write-Host "[OK] Task registered: $TaskName (Silent Mode)"
Write-Host "  Triggers: $triggerDescription"
Write-Host "  Wrapper : powershell.exe -WindowStyle Hidden -> run_check_silent.ps1"
Write-Host "  Command : $VenvPython $RunCheck"
Write-Host "  WorkDir : $ProjectDir"
Write-Host ""
Write-Host "To test manually:"
Write-Host "  Start-ScheduledTask -TaskName `"$TaskName`""
